name: shopble

networks:
  db_private_network:
    external: true

services:
  api:
    image: 127.0.0.1:5000/shopble:latest
    command: ["serve", "--host", "0.0.0.0", "--port", "8080"]
    networks:
      - db_private_network
    environment:
      CONFIG_PATH: /etc/shopble/config.yml
      DB_CONNECTION: ${DB_CONNECTION}
      SHOPBLE_OPERATOR_SECRET: ${SHOPBLE_OPERATOR_SECRET}
    volumes:
      - /opt/shopble/config.yml:/etc/shopble/config.yml:ro
    ports:
      - "${API_PORT:-8081}:8080"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
      update_config:
        order: stop-first
